export function ReportHeader() {
  return (
    <div className="flex items-center gap-4 border-b pb-3 mb-4 print:mb-6">
      <img 
        src="/brand/clearcase-mark.png?v=2" 
        alt="ClearCase" 
        className="h-8 w-auto print:h-10" 
      />
      <div className="flex-1">
        <h1 className="text-xl font-semibold text-foreground print:text-black">
          Workplace Incident Report
        </h1>
        <p className="text-sm text-muted-foreground print:text-gray-600">
          Generated by ClearCase
        </p>
      </div>
    </div>
  );
}