// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://higuokkqenvesmexzozx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZ3Vva2txZW52ZXNtZXh6b3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzkzNzMsImV4cCI6MjA3MDI1NTM3M30.rseR6QKW6KpPAIFCzwLTSBqGbyFHGpnLoUc_rHuRQ_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});